packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'

yarnPath: .yarn/releases/yarn-rc.js
