name: 'main'

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/main.yaml'
      - '.github/RELEASE_DRAFT*'
      - 'package.json'
      - 'src/**'
      - 'tests/*'
      - 'tsconfig.json'
      - 'tslint.json'
  pull_request:
    paths:
      - '.github/workflows/main.yaml'
      - '.github/RELEASE_DRAFT*'
      - 'package.json'
      - 'src/**'
      - 'tests/*'
      - 'tsconfig.json'
      - 'tslint.json'
  workflow_dispatch:

jobs:
  test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2.3.4
      - name: Lint code
        run: yarn lint
      - name: Test code
        run: yarn test
  release:
    if: github.ref == 'refs/heads/main'
    needs: test
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Create Release
        uses: darioblanco/release-wizard@main
        with:
          templatePath: RELEASE_DRAFT/default.md
          token: ${{ github.token }}
          withV: true
